### ISSUE TITLE
Silverlight unit test runner crashes while searching the container

### ISSUE THREAD

**Issue by dennisdoomen** [Erwinvandervalk/Chill#26]
When opening the current [FluentAssertions](https://github.com/dennisdoomen/fluentassertions) solution from its _develop_ branch and then starting the `Silverlight.Specs` project, the Silverlight unit test runner will crash with the following exception:

```
Unhandled Error in Silverlight Application 
Code: 4004    
Category: ManagedRuntimeError       
Message: System.MethodAccessException: Attempt by method 'Chill.TestBase.BuildInitializer()' to access method 'Chill.DefaultChillContainerInitializer`1<System.__Canon>..ctor()' failed.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at Chill.TestBase.BuildInitializer()
   at Chill.GivenWhenThen..ctor()
   at FluentAssertions.Specs.AssertionOptionsSpecs.Given_temporary_global_assertion_options..ctor()

   at FluentAssertions.Specs.AssertionOptionsSpecs.When_assertion_doubles_should_always_allow_small_deviations..ctor()
```

**Comment by dennisdoomen** [comment]
Found the issue. The AutofacChillContainer is `internal` and from my own experience, Silverlight is a bit more strict here. The solution is to either make that container `public` or to add the `InternalsVisibleTo` attribute somewhere.
